"""empty message

Revision ID: 6d5933b0c08e
Revises: 9550a345ef93
Create Date: 2020-01-06 15:31:16.671696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5933b0c08e'
down_revision = '9550a345ef93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'clients', ['id'])
    op.create_unique_constraint(None, 'clients', ['uid'])
    op.create_unique_constraint(None, 'events', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='unique')
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_constraint(None, 'clients', type_='unique')
    # ### end Alembic commands ###
