"""empty message

Revision ID: c694f7e73c46
Revises: 6d5933b0c08e
Create Date: 2020-01-14 22:39:35.463208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c694f7e73c46'
down_revision = '6d5933b0c08e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('club', sa.String(), nullable=True))
    op.add_column('events', sa.Column('description_html', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'location')
    op.drop_column('events', 'description_html')
    op.drop_column('events', 'club')
    # ### end Alembic commands ###
